import Foundation
import SwiftInferCLI
import SwiftInferCore
import SwiftInferTemplates
import Testing

/// TestLifter M8.1 + M8.2 acceptance — `swift-infer convert-counterexample`
/// CLI subcommand. Closes PRD §3.6 step 6 + §7.9 row M8 by routing
/// the user's counterexample through the matching M8.0 regression
/// arm and writing the resulting stub to
/// `<package-root>/Tests/Generated/SwiftInfer/<template>/
/// <callee>_regression_<hash>.swift`.
@Suite("ConvertCounterexample — CLI surface (M8.1)")
struct ConvertCounterexampleCLITests {

    typealias Args = ConvertCounterexampleEngine.Args

    @Test("idempotence template writes a regression stub at the conventional path")
    func idempotenceWritesAtConventionalPath() throws {
        let packageRoot = try makeFixture(name: "Idempotence")
        defer { try? FileManager.default.removeItem(at: packageRoot) }

        let args = Args(
            template: "idempotence",
            callee: "normalize",
            type: "String",
            counterexample: "\"hello\\n\""
        )
        let stub = try ConvertCounterexampleEngine.renderRegressionStub(args: args)
        let path = try ConvertCounterexampleEngine.writeRegressionStub(
            args: args, stub: stub, packageRoot: packageRoot
        )

        let hash = LiftedTestEmitter.regressionFileHash(for: "\"hello\\n\"")
        let expected = packageRoot
            .appendingPathComponent("Tests/Generated/SwiftInfer/idempotence")
            .appendingPathComponent("normalize_regression_\(hash).swift")
        #expect(path.standardizedFileURL == expected.standardizedFileURL)
        let written = try String(contentsOf: path, encoding: .utf8)
        #expect(written.contains("Auto-generated by `swift-infer convert-counterexample`"))
        #expect(written.contains("@Test func normalize_isIdempotent_regression_\(hash)()"))
        #expect(written.contains("let value: String = \"hello\\n\""))
        #expect(written.contains("#expect(normalize(normalize(value)) == normalize(value))"))
    }

    @Test("round-trip template requires --reverse-callee")
    func roundTripRequiresReverseCallee() throws {
        let args = Args(
            template: "round-trip", callee: "encode", type: "Int", counterexample: "42"
        )
        do {
            _ = try ConvertCounterexampleEngine.renderRegressionStub(args: args)
            Issue.record("Expected validation error for missing --reverse-callee")
        } catch {
            #expect("\(error)".contains("--reverse-callee"))
        }
    }

    @Test("round-trip template with --reverse-callee writes the regression stub")
    func roundTripWritesWithReverseCallee() throws {
        let packageRoot = try makeFixture(name: "RoundTrip")
        defer { try? FileManager.default.removeItem(at: packageRoot) }

        let args = Args(
            template: "round-trip",
            callee: "encode",
            type: "Int",
            counterexample: "42",
            reverseCallee: "decode"
        )
        let stub = try ConvertCounterexampleEngine.renderRegressionStub(args: args)
        let path = try ConvertCounterexampleEngine.writeRegressionStub(
            args: args, stub: stub, packageRoot: packageRoot
        )
        let written = try String(contentsOf: path, encoding: .utf8)
        #expect(written.contains("@Test func encode_decode_roundTrip_regression_"))
        #expect(written.contains("let value: Int = 42"))
        #expect(written.contains("#expect(decode(encode(value)) == value)"))
    }

    @Test("invariant-preservation template requires --invariant-keypath")
    func invariantPreservationRequiresKeypath() throws {
        let args = Args(
            template: "invariant-preservation",
            callee: "adjust",
            type: "Widget",
            counterexample: "Widget(isValid: true)"
        )
        do {
            _ = try ConvertCounterexampleEngine.renderRegressionStub(args: args)
            Issue.record("Expected validation error for missing --invariant-keypath")
        } catch {
            #expect("\(error)".contains("--invariant-keypath"))
        }
    }

    @Test("commutativity / associativity build tuple types from --type")
    func commutativityBuildsTupleType() throws {
        let packageRoot = try makeFixture(name: "Commutativity")
        defer { try? FileManager.default.removeItem(at: packageRoot) }

        let args = Args(
            template: "commutativity",
            callee: "merge",
            type: "[Int]",
            counterexample: "([1, 2], [3, 4])"
        )
        let stub = try ConvertCounterexampleEngine.renderRegressionStub(args: args)
        let path = try ConvertCounterexampleEngine.writeRegressionStub(
            args: args, stub: stub, packageRoot: packageRoot
        )
        let written = try String(contentsOf: path, encoding: .utf8)
        #expect(written.contains("let pair: ([Int], [Int]) = ([1, 2], [3, 4])"))
        #expect(written.contains("merge(pair.0, pair.1) == merge(pair.1, pair.0)"))
    }

    @Test("identity-element requires --identity-element")
    func identityElementRequiresIdentityName() throws {
        let args = Args(
            template: "identity-element", callee: "union", type: "IntSet", counterexample: "IntSet([1])"
        )
        do {
            _ = try ConvertCounterexampleEngine.renderRegressionStub(args: args)
            Issue.record("Expected validation error for missing --identity-element")
        } catch {
            #expect("\(error)".contains("--identity-element"))
        }
    }

    @Test("reduce-equivalence requires --seed-source AND --reduce-element-type")
    func reduceEquivalenceRequiresSeedAndElementType() throws {
        let args = Args(
            template: "reduce-equivalence", callee: "+", type: "Int", counterexample: "[1, 2, 3]"
        )
        do {
            _ = try ConvertCounterexampleEngine.renderRegressionStub(args: args)
            Issue.record("Expected validation error for missing required flags")
        } catch {
            let msg = "\(error)"
            #expect(msg.contains("--reduce-element-type") || msg.contains("--seed-source"))
        }
    }

    @Test("Unknown --template errors with the valid-templates list")
    func unknownTemplateErrors() throws {
        let args = Args(template: "bogus", callee: "f", type: "Int", counterexample: "0")
        do {
            _ = try ConvertCounterexampleEngine.renderRegressionStub(args: args)
            Issue.record("Expected validation error for unknown --template")
        } catch {
            let msg = "\(error)"
            #expect(msg.contains("unknown --template") || msg.contains("bogus"))
            #expect(msg.contains("idempotence"))
            #expect(msg.contains("round-trip"))
        }
    }

    @Test("Re-running with the same args is idempotent (byte-stable file output)")
    func rerunIsIdempotent() throws {
        let packageRoot = try makeFixture(name: "Idempotent")
        defer { try? FileManager.default.removeItem(at: packageRoot) }

        let args = Args(
            template: "idempotence", callee: "normalize", type: "String", counterexample: "\"hello\""
        )
        let firstStub = try ConvertCounterexampleEngine.renderRegressionStub(args: args)
        let firstPath = try ConvertCounterexampleEngine.writeRegressionStub(
            args: args, stub: firstStub, packageRoot: packageRoot
        )
        let firstContents = try String(contentsOf: firstPath, encoding: .utf8)

        let secondStub = try ConvertCounterexampleEngine.renderRegressionStub(args: args)
        let secondPath = try ConvertCounterexampleEngine.writeRegressionStub(
            args: args, stub: secondStub, packageRoot: packageRoot
        )
        let secondContents = try String(contentsOf: secondPath, encoding: .utf8)

        #expect(firstPath == secondPath)
        #expect(firstContents == secondContents)
    }

    @Test("Different counterexamples produce distinct files")
    func differentCounterexamplesProduceDistinctFiles() throws {
        let packageRoot = try makeFixture(name: "Distinct")
        defer { try? FileManager.default.removeItem(at: packageRoot) }

        let args1 = Args(
            template: "idempotence", callee: "normalize", type: "String", counterexample: "\"hello\""
        )
        let args2 = Args(
            template: "idempotence", callee: "normalize", type: "String", counterexample: "\"goodbye\""
        )
        let path1 = try ConvertCounterexampleEngine.writeRegressionStub(
            args: args1,
            stub: try ConvertCounterexampleEngine.renderRegressionStub(args: args1),
            packageRoot: packageRoot
        )
        let path2 = try ConvertCounterexampleEngine.writeRegressionStub(
            args: args2,
            stub: try ConvertCounterexampleEngine.renderRegressionStub(args: args2),
            packageRoot: packageRoot
        )
        #expect(path1 != path2)
        #expect(FileManager.default.fileExists(atPath: path1.path))
        #expect(FileManager.default.fileExists(atPath: path2.path))
    }
}

/// TestLifter M8.2 acceptance — `convert-counterexample` writeouts
/// stay rooted under `<package-root>/Tests/Generated/SwiftInfer/`.
/// Mirrors the M3.3 / M5.6 / M6.3 §16 #1 hard-guarantee tests.
@Suite("ConvertCounterexample — §16 #1 sandbox guarantee (M8.2)")
struct ConvertCounterexampleSandboxTests {

    typealias Args = ConvertCounterexampleEngine.Args

    @Test("Writeout stays under <package-root>/Tests/Generated/SwiftInfer/")
    func writeoutStaysSandboxed() throws {
        let packageRoot = try makeFixture(name: "Sandbox")
        defer { try? FileManager.default.removeItem(at: packageRoot) }

        let args = Args(
            template: "round-trip",
            callee: "encode",
            type: "Int",
            counterexample: "42",
            reverseCallee: "decode"
        )
        let path = try ConvertCounterexampleEngine.writeRegressionStub(
            args: args,
            stub: try ConvertCounterexampleEngine.renderRegressionStub(args: args),
            packageRoot: packageRoot
        )
        let stubsRoot = packageRoot
            .appendingPathComponent("Tests/Generated/SwiftInfer")
            .standardizedFileURL
            .path
        let written = path.standardizedFileURL.path
        #expect(
            written.hasPrefix(stubsRoot + "/"),
            "convert-counterexample writeout escaped Tests/Generated/SwiftInfer/: \(written)"
        )
    }

    @Test("Writeout is the only new file under packageRoot after the run")
    func writeoutIsTheOnlyNewFile() throws {
        let packageRoot = try makeFixture(name: "OnlyNew")
        defer { try? FileManager.default.removeItem(at: packageRoot) }

        let beforeFiles = try fileSet(in: packageRoot)
        let args = Args(
            template: "idempotence", callee: "normalize", type: "String", counterexample: "\"x\""
        )
        _ = try ConvertCounterexampleEngine.writeRegressionStub(
            args: args,
            stub: try ConvertCounterexampleEngine.renderRegressionStub(args: args),
            packageRoot: packageRoot
        )
        let afterFiles = try fileSet(in: packageRoot)
        let newFiles = Set(afterFiles).subtracting(beforeFiles)
        #expect(newFiles.count == 1)
        let stubsRoot = packageRoot
            .appendingPathComponent("Tests/Generated/SwiftInfer")
            .standardizedFileURL
            .path
        for newFile in newFiles {
            #expect(newFile.standardizedFileURL.path.hasPrefix(stubsRoot + "/"))
        }
    }
}

// MARK: - Shared fixture helpers

private func makeFixture(name: String) throws -> URL {
    let base = FileManager.default.temporaryDirectory
        .appendingPathComponent("ConvertCEX-\(name)-\(UUID().uuidString)")
    try FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
    return base
}

private func fileSet(in directory: URL) throws -> [URL] {
    let manager = FileManager.default
    guard let enumerator = manager.enumerator(
        at: directory,
        includingPropertiesForKeys: [.isRegularFileKey],
        options: [.skipsHiddenFiles]
    ) else {
        return []
    }
    var files: [URL] = []
    for case let url as URL in enumerator {
        var isDir: ObjCBool = false
        manager.fileExists(atPath: url.path, isDirectory: &isDir)
        if !isDir.boolValue {
            files.append(url)
        }
    }
    return files.sorted { $0.path < $1.path }
}
