import Foundation
@testable import SwiftInferCLI
import SwiftInferCore
import SwiftInferTemplates
import Testing

/// A stub file, end to end, as `discover --interactive` writes it — pinned whole, because what is
/// being pinned is its *shape*: the one SwiftLint reads.
///
/// The input is the shape the SwiftLintRuleStudio road test wrote on 2026-10-08
/// (`CompatibilityReport_hasIssues_emptiness-agreement.swift`), which drew 13 violations under
/// that project's config: `type_name` and `file_name` from the underscored names, `sorted_imports`,
/// `vertical_whitespace` from three blank header lines, `line_length` from an absolute `// Source:`
/// path and a 404-character generator line, and `closure_end_indentation` from the kit's
/// `\n.map { … }` continuation leaving the sample closure's brace mid-line. The golden below lints
/// clean under that config with SwiftLint 0.65.1, and builds and runs in that package with the
/// same verdict as the file it replaces.
@Suite("Generated stub files — the lint-clean shape, pinned")
struct GeneratedStubLintGoldenTests {

    /// The kit's memberwise rendering — a `zip(…)` with its `.map` on a continuation line.
    static let memberwiseGenerator = "zip(Gen<Character>.letterOrNumber.string(of: 0...8), "
        + "zip(Gen<Character>.letterOrNumber.string(of: 0...8), Gen<Character>.letterOrNumber.string(of: 0...8), "
        + "Gen<Character>.letterOrNumber.string(of: 0...8).optional)\n"
        + "                .map { DeprecatedRuleInfo(id: $0.0, ruleId: $0.1, replacement: $0.2) }.array(of: 0...8), "
        + "Gen<Character>.letterOrNumber.string(of: 0...8).array(of: 0...8))\n"
        + "                .map { CompatibilityReport(swiftLintVersion: $0.0, deprecatedRules: $0.1, "
        + "availableNewRules: $0.2) }"

    static let checker = "VersionCompatibilityChecker"

    static func member(_ name: String, line: Int) -> Evidence {
        Evidence(
            displayName: name,
            signature: "() -> Bool",
            location: SourceLocation(file: "/work/Core/Sources/Core/Services/\(checker).swift", line: line, column: 9),
            isInstanceMethod: true,
            isComputedProperty: true,
            qualifiedTypeName: "CompatibilityReport",
            globalActor: "MainActor"
        )
    }

    static let suggestion = Suggestion(
        templateName: "emptiness-agreement",
        evidence: [member("hasIssues()", line: 79), member("totalIssueCount()", line: 74)],
        score: Score(signals: [Signal(kind: .exactNameMatch, weight: 20, detail: "w")]),
        generator: GeneratorMetadata(source: .derivedMemberwise, confidence: nil, sampling: .notRun),
        explainability: ExplainabilityBlock(whySuggested: [], whyMightBeWrong: []),
        identity: SuggestionIdentity(canonicalInput: "CompatibilityReport.hasIssues::emptiness-agreement")
    )

    static func writtenFile() throws -> (name: String, contents: String) {
        let generator: (String) -> String? = { $0 == "CompatibilityReport" ? memberwiseGenerator : nil }
        let stub = try #require(InteractiveTriage.emptinessAgreementStub(for: suggestion, customGenerator: generator))
        let name = try #require(InteractiveTriage.stubFileName(for: suggestion))
        let contents = InteractiveTriage.wrappedFileContents(
            stub: stub,
            suggestion: suggestion,
            moduleUnderTest: "Core",
            fileName: name,
            packageRoot: URL(fileURLWithPath: "/work/Core")
        )
        return (name, contents)
    }

    @Test func theFileIsNamedForTheSuiteItDeclares() throws {
        let file = try Self.writtenFile()
        #expect(file.name == "CompatibilityReportHasIssuesEmptinessAgreementTests.swift")
        #expect(file.contents.contains("\nstruct CompatibilityReportHasIssuesEmptinessAgreementTests {\n"))
    }

    @Test func theWholeFile() throws {
        let file = try Self.writtenFile()
        #expect(file.contents == Self.golden)
    }

    @Test func theFileParsesAndEveryLineFits() throws {
        let file = try Self.writtenFile()
        #expect(GeneratedFileLayout.parses(file.contents.components(separatedBy: "\n")))
        let lines = file.contents.split(separator: "\n", omittingEmptySubsequences: false)
        #expect(lines.allSatisfy { $0.count <= GeneratedFileLayout.lineLimit })
        #expect(!file.contents.contains("\n\n\n"))
        #expect(file.contents.hasSuffix("}\n") && !file.contents.hasSuffix("\n\n"))
    }

    static let golden = """
    // Auto-generated by `swift-infer discover --interactive` — do not edit.
    // Source: Sources/Core/Services/VersionCompatibilityChecker.swift:79
    // Suggestion identity: 0x7DD1204439A894DA
    // Template: emptiness-agreement
    // Law class: CONJECTURE — read from the signature and the name, not entailed by either,
    //            so a CORRECT implementation can fail it. A pass means no counterexample was
    //            found in the trials drawn, NOT that the law holds: a law whose
    //            counterexamples lie outside the generator's reach passes while being false.

    @testable import Core
    import Foundation
    import PropertyBased
    import PropertyLawKit
    import Testing
    struct CompatibilityReportHasIssuesEmptinessAgreementTests {

        nonisolated private static let generator = zip(
            Gen<Character>.letterOrNumber.string(of: 0...8),
            zip(
                Gen<Character>.letterOrNumber.string(of: 0...8), Gen<Character>.letterOrNumber.string(of: 0...8),
                Gen<Character>.letterOrNumber.string(of: 0...8).optional
            )
            .map { DeprecatedRuleInfo(id: $0.0, ruleId: $0.1, replacement: $0.2) }
            .array(of: 0...8),
            Gen<Character>.letterOrNumber.string(of: 0...8).array(of: 0...8)
        ).map { CompatibilityReport(swiftLintVersion: $0.0, deprecatedRules: $0.1, availableNewRules: $0.2) }

        @Test func hasIssues_agreesWith_totalIssueCount() async {
            let backend = SwiftPropertyBasedBackend()
            let seed = Seed(
                stateA: 0x881ABDEFEF72B6FA,
                stateB: 0x262FD1F8C18F12CD,
                stateC: 0xCB6C7DFC55764C46,
                stateD: 0x0D06215186670AD6
            )
            let result = await backend.check(
                trials: 100,
                seed: seed,
                sample: { rng in Self.generator.run(using: &rng) },
                property: { (value: CompatibilityReport) in
                    await MainActor.run { value.hasIssues == (value.totalIssueCount > 0) }
                }
            )
            if case let .failed(_, _, input, error) = result {
                Issue.record(
                    "hasIssues disagrees with totalIssueCount > 0 at input \\(input). \\(error?.message ?? "")"
                )
            }
        }
    }

    """
}
