#!/usr/bin/env python3
"""Re-run a mutation-check record's string-literal (M6) mutants against a newer census's stubs.

    literal_mutant_rerun.py <old-scratch-root> <new-trees-dir> <out.jsonl> [operator-prefixes]

`<old-scratch-root>` is the directory holding the census trees `sample.json` names
(`census-widened/`, `census-imports2/`); `<new-trees-dir>` is a later census's `trees/`, whose stubs
were regenerated by the binary under test. Each recorded patch is applied with `git apply` and reverted
whatever happens, so the new tree need not sit at the recorded commit — only accept the patch.
Used for `docs/plans/subject-literal-generation-scope.md` §4c.
"""
import json, os, subprocess, sys
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "scripts"))
import mutation_check as mc  # noqa: E402

OLD = os.path.join(sys.argv[1], "")
B = os.path.join(sys.argv[2], "")
OUT = sys.argv[3]
# Which recorded mutants to re-run, by operator prefix: `M6` (the default, §4c's literal mutants), or a
# comma list such as `M1,M4` for the boundary classes `docs/measurements/boundary-reach.md` re-runs.
OPERATORS = tuple((sys.argv[4] if len(sys.argv) > 4 else "M6").split(","))
# Optional: only these suites (comma list), to re-measure one stub after regenerating it.
SUITES = set(sys.argv[5].split(",")) if len(sys.argv) > 5 else None

laws = {l["suite"]: l for l in json.load(open(os.path.join(REPO, "fixtures/mutation-check/sample.json")))["laws"]}
rows = [r for r in map(json.loads, open(os.path.join(REPO, "fixtures/mutation-check/run-2026-09-22.jsonl")))
        if r["kind"] == "mutant" and r["operator"].startswith(OPERATORS)
        and (SUITES is None or r["suite"] in SUITES)]


def rebase(path):
    for old in ("census-widened/trees/", "census-imports2/trees/"):
        if (OLD + old) in path:
            return os.path.normpath(B + path.split(OLD + old, 1)[1])
    raise ValueError(path)


def git(tree, *args, stdin=None):
    return subprocess.run(["git", "-C", tree, *args], input=stdin, capture_output=True, text=True)


out = open(OUT, "a")
def emit(record):
    out.write(json.dumps(record) + "\n"); out.flush(); print(json.dumps(record), flush=True)

runnable = []
for row in rows:
    law = dict(laws[row["suite"]])
    for key in ("package", "stub", "source"):
        law[key] = rebase(law[key])
    tree = os.path.join(B, row["repo"])
    head = git(tree, "rev-parse", "HEAD").stdout.strip()
    base = dict(suite=row["suite"], repo=row["repo"], template=row["template"], was=row["outcome"],
                recorded_commit=row["commit"][:8], tree_commit=head[:8])
    if row["outcome"] == "DISCARDED":
        emit(dict(base, now="DISCARDED", note="did not compile in the recorded run")); continue
    if not os.path.exists(law["stub"]):
        emit(dict(base, now="WITHDRAWN", note="no stub in census-B")); continue
    if git(tree, "apply", "--check", "-", stdin=row["patch"]).returncode != 0:
        emit(dict(base, now="PATCH-MISMATCH")); continue
    runnable.append((row, law, tree, base))

for package, group in mc.itertools_groupby([dict(l, _i=i) for i, (_, l, _, _) in enumerate(runnable)], "package"):
    mc.install(group)
    swift = mc.swift_for(group[0])
    ok, log = mc.build(package, swift)
    if not ok:
        for law in group:
            emit(dict(runnable[law["_i"]][3], now="BASELINE-BUILD-FAILED", detail=log[-400:]))
        continue
    for law in group:
        row, _, tree, base = runnable[law["_i"]]
        first = mc.evaluate(law, swift)
        second = mc.run_suite(package, swift, law["suite"] + "_Probe", law["test"])[1] if law.get("probe") else None
        baseline = dict(first, deterministic=(second == first.get("probe")) if law.get("probe") else None)
        record = dict(base, baseline_law=baseline["law"], baseline_law1000=baseline.get("law1000"))
        if baseline["law"] != "passed":
            emit(dict(record, now="BASELINE-" + baseline["law"].upper())); continue
        git(tree, "apply", "-", stdin=row["patch"])
        try:
            ok, _ = mc.build(package, swift)
            mutant = dict(compiles=ok, **(mc.evaluate(law, swift) if ok else {}))
        finally:
            git(tree, "apply", "-R", "-", stdin=row["patch"])
        emit(dict(record, law=mutant.get("law"), law1000=mutant.get("law1000"),
                  now=mc.score(mutant, baseline)))
    mc.build(package, swift)
