import Foundation
import SwiftInferCore

/// Accept-path for M16.3 consumer-producer chain advisory suggestions
/// (PRD §7.8 second example, generalized). Comment-only documentation
/// block — no `@Test func` body, no runnable property; M10 owns the
/// generator-override surface for the round-trip-pair subset (M16
/// plan §"M16 explicitly defers"). Mirrors
/// `InteractiveTriage+AcceptEquivalenceClass.swift`'s shape.
extension InteractiveTriage {

    /// M16.3 — writeout for consumer-producer chain advisory
    /// suggestions. File path: `<outputDir>/Tests/Generated/SwiftInfer/consumer-producer/<consumer>_<producer>.swift`.
    /// The directory is sibling to `equivalence-class/` so the path-
    /// collision concern raised in the M16 plan OD #1 is resolved at
    /// the source. Honors `dryRun`.
    static func writeConsumerProducerChainDocument(
        hint: DomainHint,
        context: Context
    ) throws -> URL? {
        let fileName = "\(hint.reverseName)_\(hint.producerName).swift"
        let path = context.outputDirectory
            .appendingPathComponent("Tests/Generated/SwiftInfer/consumer-producer/\(fileName)")
        if context.dryRun {
            context.output.write("[dry-run] would write \(path.path)")
            return nil
        }
        let contents = consumerProducerChainFileContents(hint: hint)
        try FileManager.default.createDirectory(
            at: path.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try Data(contents.utf8).write(to: path, options: .atomic)
        context.output.write("Wrote \(path.path)")
        return path
    }

    /// Formats the comment-only documentation block for a consumer-
    /// producer chain. Names the chain (`<consumer> ← <producer>`),
    /// the site count, the producer-veto reason if any (mirroring
    /// M10's vetoed-render path), and a closing caveat about the
    /// observation being a domain narrowing rather than a runnable
    /// property.
    static func consumerProducerChainFileContents(hint: DomainHint) -> String {
        var lines: [String] = []
        lines.append("// Auto-generated by `swift-infer discover --interactive` — do not edit.")
        lines.append("//")
        let header = "// Inferred consumer-producer chain: "
            + "\(hint.reverseName) ← \(hint.producerName)"
        lines.append(header)
        lines.append("//")
        let observation = "// \(hint.reverseName)'s argument was always \(hint.producerName)'s output"
            + " across \(hint.siteCount) test sites — domain narrowing observed."
        lines.append(observation)
        lines.append("//")
        if let veto = hint.producerVeto {
            lines.append("// Generator narrowing skipped: \(veto.advisoryReason).")
        } else {
            lines.append("// Suggested narrowed generator: \(hint.suggestedGenerator)")
        }
        lines.append("//")
        let caveat = "// Caveat: this is documentation only. \(hint.reverseName) may also"
            + " be intended for arbitrary \(hint.domainTypeName)s outside \(hint.producerName)'s"
            + " range; if so, author a separate property exercising the broader domain."
        lines.append(caveat)
        return lines.joined(separator: "\n") + "\n"
    }
}
