import Foundation
import SwiftInferCore

/// Accept-path for M11.2 equivalence-class advisory suggestions
/// (PRD §7.8 third example). Comment-only documentation block —
/// no `@Test func` body, no runnable property. Split out of
/// `InteractiveTriage+Accept.swift` to keep that file under SwiftLint's
/// 400-line cap (the M11.2-budget-fix side-map dispatch + the writeout
/// helpers crossed the threshold).
extension InteractiveTriage {

    /// M11.2 — writeout for equivalence-class advisory suggestions.
    /// File path: `<outputDir>/Tests/Generated/SwiftInfer/equivalence-class/EquivalenceClasses_<predicate>.swift`.
    /// Honors `dryRun`.
    static func writeEquivalenceClassDocument(
        hint: EquivalenceClassHint,
        context: Context
    ) throws -> URL? {
        let fileName = "EquivalenceClasses_\(hint.predicateName).swift"
        let path = context.outputDirectory
            .appendingPathComponent("Tests/Generated/SwiftInfer/equivalence-class/\(fileName)")
        if context.dryRun {
            context.output.write("[dry-run] would write \(path.path)")
            return nil
        }
        let contents = equivalenceClassFileContents(hint: hint)
        try FileManager.default.createDirectory(
            at: path.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try Data(contents.utf8).write(to: path, options: .atomic)
        context.output.write("Wrote \(path.path)")
        return path
    }

    /// Formats the comment-only documentation block for an
    /// equivalence-class suggestion. Lists both bucket counts, the
    /// suggested filter generators (or the veto reason when the
    /// predicate is throws / async / multi-arg / non-generatable arg),
    /// and a caveat about filter rejection rate.
    static func equivalenceClassFileContents(hint: EquivalenceClassHint) -> String {
        var lines: [String] = []
        lines.append("// Auto-generated by `swift-infer discover --interactive` — do not edit.")
        lines.append("//")
        let header = "// Inferred predicate equivalence class for "
            + "\(hint.predicateName)(_: \(hint.argTypeName)) -> Bool"
        lines.append(header)
        lines.append("//")
        let positive = "//   • \(hint.positiveSiteCount) test methods named \(hint.positiveMarker)*"
            + " assert \(hint.predicateName)(x) is true"
        lines.append(positive)
        let negative = "//   • \(hint.negativeSiteCount) test methods named \(hint.negativeMarker)*"
            + " assert \(hint.predicateName)(x) is false"
        lines.append(negative)
        lines.append("//")
        if let veto = hint.predicateVeto {
            lines.append("// Generator narrowing skipped: \(veto.advisoryReason).")
        } else {
            let posGen = "// Suggested generator for \(hint.positiveMarker) class: "
                + hint.suggestedPositiveGenerator
            let negGen = "// Suggested generator for \(hint.negativeMarker) class: "
                + hint.suggestedNegativeGenerator
            lines.append(posGen)
            lines.append(negGen)
        }
        lines.append("//")
        if hint.coversDomain {
            lines.append("// Exhaustiveness: forAll x: \(hint.argTypeName)."
                + " \(hint.predicateName)(x) ∨ ¬\(hint.predicateName)(x)"
                + " — partition syntactically covers \(hint.argTypeName).")
            lines.append("//")
        }
        let caveat = "// Caveat: \(hint.predicateName) may reject most random"
            + " \(hint.argTypeName)s; if so, prefer constructing a custom Gen for the"
            + " \(hint.positiveMarker) class instead of relying on filter."
        lines.append(caveat)
        return lines.joined(separator: "\n") + "\n"
    }

    /// M13.3 — writeout for N-class equivalence-class advisory
    /// suggestions. File path:
    /// `<outputDir>/Tests/Generated/SwiftInfer/equivalence-class/EquivalenceClasses_<predicate>_<markerSetName>.swift`.
    /// The marker-set-name suffix disambiguates when the same predicate
    /// fires under multiple marker sets (M13 plan OD #6). Honors `dryRun`.
    static func writeNClassEquivalenceClassDocument(
        hint: NClassEquivalenceClassHint,
        context: Context
    ) throws -> URL? {
        let suffix = hint.markerSetName.lowercased()
        let fileName = "EquivalenceClasses_\(hint.predicateName)_\(suffix).swift"
        let path = context.outputDirectory
            .appendingPathComponent("Tests/Generated/SwiftInfer/equivalence-class/\(fileName)")
        if context.dryRun {
            context.output.write("[dry-run] would write \(path.path)")
            return nil
        }
        let contents = nClassEquivalenceClassFileContents(hint: hint)
        try FileManager.default.createDirectory(
            at: path.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try Data(contents.utf8).write(to: path, options: .atomic)
        context.output.write("Wrote \(path.path)")
        return path
    }

    /// M13.3 — N-class comment-only documentation block. Lists per-bucket
    /// counts, the suggested per-bucket filter generators (or the veto
    /// reason when the predicate fails the M13.2 veto checks), and an
    /// exhaustiveness comment when `coversDomain == true`.
    static func nClassEquivalenceClassFileContents(hint: NClassEquivalenceClassHint) -> String {
        var lines: [String] = []
        lines.append("// Auto-generated by `swift-infer discover --interactive` — do not edit.")
        lines.append("//")
        let header = "// Inferred N-class equivalence partition for "
            + "\(hint.predicateName)(_: \(hint.argTypeName)) -> \(hint.returnTypeName)"
            + " across \(hint.markerSetName)"
        lines.append(header)
        lines.append("//")
        for marker in hint.markers {
            let count = hint.siteCountsByMarker[marker] ?? 0
            let line = "//   • \(count) test methods named \(marker)*"
                + " assert \(hint.predicateName)(x) is .\(lowercaseFirst(marker))"
            lines.append(line)
        }
        lines.append("//")
        if let veto = hint.predicateVeto {
            lines.append("// Generator narrowing skipped: \(veto.advisoryReason).")
        } else {
            for marker in hint.markers {
                if let generator = hint.suggestedGeneratorsByMarker[marker] {
                    lines.append("// Suggested generator for \(marker) class: \(generator)")
                }
            }
        }
        lines.append("//")
        if hint.coversDomain {
            let cases = hint.markers.map { ".\(lowercaseFirst($0))" }.joined(separator: " ∨ p(x) == ")
            lines.append("// Exhaustiveness: forAll x: \(hint.argTypeName)."
                + " p(x) == \(cases)"
                + " — markers cover every case of \(hint.returnTypeName).")
            lines.append("//")
        }
        let caveat = "// Caveat: \(hint.predicateName) may reject most random"
            + " \(hint.argTypeName)s for any single bucket; if so, prefer"
            + " constructing custom Gens per bucket instead of relying on filter."
        lines.append(caveat)
        return lines.joined(separator: "\n") + "\n"
    }

    /// Marker text in vocabulary is conventionally Title-cased; Swift
    /// enum cases are lowercase-first. The renderer uses this when
    /// emitting `.case` literals in the comment block.
    private static func lowercaseFirst(_ text: String) -> String {
        guard let first = text.first else { return text }
        return first.lowercased() + text.dropFirst()
    }
}
