import Foundation
import SwiftInferCore

extension InteractiveTriage {

    /// Wrap the bare `@Test func` block from `LiftedTestEmitter` with
    /// the file-level imports + provenance header for the
    /// `Tests/Generated/SwiftInfer/` writeout. Lifted-origin suggestions
    /// get an extra "Lifted from" line (TestLifter M3.3) distinct from
    /// the `// Source:` assertion-site pointer.
    static func wrappedFileContents(
        stub: String,
        suggestion: Suggestion,
        packageRoot: URL? = nil
    ) -> String {
        let location = suggestion.evidence.first?.location
        let sourceLine = location.map { loc in "// Source: \(loc)" } ?? ""
        // Import the module under test so the generated file compiles drop-in.
        // `@testable` reaches internal functions (the common case for the free /
        // internal helpers seeds point at). Derived from the MANIFEST where one is
        // available, and from the SPM path convention otherwise.
        let resolvedModule = location.flatMap { loc in
            Self.moduleName(forSourceFile: loc.file, packageRoot: packageRoot)
        }
        let moduleImport = resolvedModule.map { "@testable import \($0)\n" } ?? ""
        // Says what is missing instead of emitting nothing. A dropped import used to be
        // indistinguishable from a stub that needed none, and the file read as finished —
        // 0 of 19 on SwiftMarkdownWiki carried one and nothing reported it (#415).
        // Deliberately does NOT spell the import it is asking for. `InteractiveTriageExtraction`
        // greps the emitted text for `@testable import` to tell a stub that has one from a stub
        // that does not, and so will a reader — a marker carrying the literal token makes the
        // absent case look present, which is the failure this line exists to end.
        let moduleTodo = resolvedModule == nil
            ? "// TODO: this stub has NO module import. swift-infer could not derive the module"
                + " under test from Package.swift or from the source path — add a testable"
                + " import for it before running this file.\n"
            : ""
        let liftedLine = suggestion.liftedOrigin.map { origin in
            "// Lifted from \(origin.sourceLocation)"
                + " \(origin.testMethodName)()"
        } ?? ""
        // TestLifter M4.4 — mock-inferred suggestions get a provenance
        // line surfacing construction-site count + .low confidence.
        let mockLine: String = {
            guard suggestion.generator.source == .inferredFromTests,
                  let mock = suggestion.mockGenerator else {
                return ""
            }
            return "// Mock-inferred from \(mock.siteCount) construction"
                + " site\(mock.siteCount == 1 ? "" : "s") in test bodies — low confidence"
                + " (verify the generator covers your domain)"
        }()
        // TestLifter M5.4 — Codable round-trip suggestions get a
        // provenance line surfacing the .medium confidence and the
        // user-action requirement (replacing the placeholder fixture
        // before the generator buys you a real round-trip property).
        let codableLine: String = {
            guard suggestion.generator.source == .derivedCodableRoundTrip else {
                return ""
            }
            return "// Codable round-trip generator scaffold — medium confidence"
                + " (replace the fixture inside the generator body before this"
                + " property exercises real values)"
        }()
        // M5.4 added this for the JSONEncoder / JSONDecoder calls in the Codable round-trip
        // scaffold, and only for that arm. Now unconditional: a package that enables
        // `MemberImportVisibility` requires an explicit import for any Foundation member the
        // file touches, and the generators reach Foundation freely (#415). Harmless when unused.
        let foundationImport = "import Foundation\n"
        return """
        // Auto-generated by `swift-infer discover --interactive` — do not edit.
        \(sourceLine)
        \(liftedLine)
        \(mockLine)
        \(codableLine)
        // Suggestion identity: \(suggestion.identity.display)
        // Template: \(suggestion.templateName)

        \(foundationImport)import Testing
        import PropertyBased
        import PropertyLawKit
        \(moduleImport)\(moduleTodo)\(stub)
        """
    }

    /// The module under test — **the manifest first, the path convention second**.
    ///
    /// The path rule below requires a literal `Sources/` component, and its doc comment read
    /// the `nil` case as *a synthetic fixture*. That is exactly backwards for the case
    /// `--sources` exists to serve: an Xcode-originated package puts its target at
    /// `SwiftMarkdownWiki/`, so every one of its 19 emitted stubs silently lost its import
    /// (#415). `VerifyTargetInference` has answered this question from the manifest since
    /// v1.149 and nothing on this path asked it.
    ///
    /// Falls back to the path rule when there is no package root to consult, so the synthetic
    /// fixtures the old doc comment was really about behave exactly as before.
    static func moduleName(forSourceFile path: String, packageRoot: URL?) -> String? {
        if let packageRoot {
            let declared = VerifyTargetInference.module(
                forLocation: path, packageRoot: packageRoot
            )
            if let declared { return moduleIdentifier(from: declared) }
        }
        return moduleName(fromSourceFile: path)
    }

    /// The module under test, derived from a source file path laid out the SPM
    /// way (`.../Sources/<Module>/<File>.swift`). Returns `nil` for paths with no
    /// `Sources/` component (e.g. unit-test fixtures), so the `@testable import`
    /// is added only when it can be inferred — keeping generated tests drop-in
    /// compilable for real packages without guessing for synthetic ones.
    static func moduleName(fromSourceFile path: String) -> String? {
        let components = path.split(separator: "/").map(String.init)
        guard let sourcesIndex = components.lastIndex(of: "Sources"),
              sourcesIndex + 1 < components.count else {
            return nil
        }
        let candidate = components[sourcesIndex + 1]
        return candidate.hasSuffix(".swift") ? nil : moduleIdentifier(from: candidate)
    }

    /// The Swift module name SwiftPM synthesizes for a target directory. SwiftPM
    /// replaces every character that isn't valid in a Swift identifier with `_`,
    /// so the directory `swift-clone-detector` is imported as
    /// `swift_clone_detector`. Emitting the raw directory name produced
    /// `@testable import swift-clone-detector`, which is a syntax error and broke
    /// every generated stub for a hyphen- or dot-named target.
    static func moduleIdentifier(from targetDirectory: String) -> String {
        let allowed: Set<Character> = Set(
            "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_"
        )
        return String(targetDirectory.map { allowed.contains($0) ? $0 : "_" })
    }

    static func stubFileName(for suggestion: Suggestion) -> String? {
        // TestLifter M3.3 — lifted-origin suggestions get
        // `<TestMethodName>_lifted_<TemplateName>.swift` to disambiguate
        // from TemplateEngine writeouts in the same `<template>/` dir.
        if let origin = suggestion.liftedOrigin {
            let sanitizedMethod = sanitizeForFileName(origin.testMethodName)
            let sanitizedTemplate = sanitizeForFileName(suggestion.templateName)
            return "\(sanitizedMethod)_lifted_\(sanitizedTemplate).swift"
        }
        guard let evidence = suggestion.evidence.first,
              let funcName = functionName(from: evidence.displayName) else {
            return nil
        }
        // **Every name carries its template**, because the `<template>/` directory does NOT
        // disambiguate: SwiftPM requires unique basenames within a target, so `merge.swift`
        // under `commutativity/` and under `associativity/` is
        // `error: filename "merge.swift" used twice`. One function firing two templates is
        // ordinary — `merge` fires three here — so this was not an edge case, it was every
        // subject with an algebraic operation.
        //
        // Invisible until #414: while the files sat in no target, nothing compiled them and
        // nothing could collide. The lifted arm above has disambiguated this way since M3.3
        // and its comment says why; the rule was simply never generalised.
        let template = sanitizeForFileName(suggestion.templateName)
        switch suggestion.templateName {
        case "round-trip":
            guard let reverse = suggestion.evidence.dropFirst().first,
                  let reverseName = functionName(from: reverse.displayName) else {
                return "\(funcName)_\(template).swift"
            }
            return "\(funcName)_\(reverseName)_\(template).swift"

        case "invariant-preservation":
            // File name carries the keypath suffix so distinct invariants
            // on the same function don't overwrite each other.
            guard let keyPath = invariantKeypath(from: evidence.signature) else {
                return "\(funcName)_\(template).swift"
            }
            let suffix = keyPath
                .replacingOccurrences(of: "\\.", with: "")
                .replacingOccurrences(of: ".", with: "_")
            return "\(funcName)_\(suffix)_\(template).swift"

        default:
            return "\(funcName)_\(template).swift"
        }
    }

    /// Replace `/`, whitespace, and other path-hostile characters with
    /// `_` so file-name components from `LiftedOrigin.testMethodName`
    /// or `Suggestion.templateName` (e.g. `"round-trip"` → `"round-trip"`,
    /// `"identity-element"` → `"identity-element"`) don't introduce
    /// path separators or shell-special characters into writeout paths.
    /// Hyphens are preserved — they're safe and they're the natural
    /// shape of `Suggestion.templateName` values.
    private static func sanitizeForFileName(_ raw: String) -> String {
        let allowed: Set<Character> = Set(
            "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"
        )
        return String(raw.map { allowed.contains($0) ? $0 : "_" })
    }
}
