import Foundation
import SwiftInferCore
import SwiftInferTemplates

/// Accept-path helpers + suggestion-field extraction for
/// `InteractiveTriage` (M6.4). Split out to keep the main enum body
/// under SwiftLint's 250-line cap; nothing here is part of the
/// public surface.
extension InteractiveTriage {

    // MARK: - Accept-path file write

    /// Returns the URL written to (or `nil` when no file was written
    /// — dry-run, unsupported template arm, or extraction failure).
    static func handleAccept(
        suggestion: Suggestion,
        context: Context
    ) throws -> URL? {
        guard let stub = liftedTestStub(for: suggestion) else {
            context.diagnostics.writeDiagnostic(
                "note: no stub writeout available for template '\(suggestion.templateName)' in v1; "
                    + "decision recorded without writing a file"
            )
            return nil
        }
        let fileName = stubFileName(for: suggestion) ?? "\(suggestion.identity.normalized).swift"
        let path = context.outputDirectory
            .appendingPathComponent("Tests/Generated/SwiftInfer/\(suggestion.templateName)/\(fileName)")
        if context.dryRun {
            context.output.write("[dry-run] would write \(path.path)")
            return nil
        }
        let contents = wrappedFileContents(stub: stub, suggestion: suggestion)
        try FileManager.default.createDirectory(
            at: path.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try Data(contents.utf8).write(to: path, options: .atomic)
        context.output.write("Wrote \(path.path)")
        return path
    }

    /// Build the lifted-test source text for `suggestion` if its
    /// template arm has a `LiftedTestEmitter` writeout in v1. M6.3
    /// ships only `idempotent` + `roundTrip`; the other three
    /// templates (commutativity, associativity, identity-element)
    /// return `nil`.
    private static func liftedTestStub(for suggestion: Suggestion) -> String? {
        switch suggestion.templateName {
        case "idempotence":
            return idempotentStub(for: suggestion)
        case "round-trip":
            return roundTripStub(for: suggestion)
        default:
            return nil
        }
    }

    private static func idempotentStub(for suggestion: Suggestion) -> String? {
        guard let evidence = suggestion.evidence.first,
              let funcName = functionName(from: evidence.displayName),
              let typeName = paramType(from: evidence.signature) else {
            return nil
        }
        let seed = SamplingSeed.derive(from: suggestion.identity)
        return LiftedTestEmitter.idempotent(
            funcName: funcName,
            typeName: typeName,
            seed: seed,
            generator: LiftedTestEmitter.defaultGenerator(for: typeName)
        )
    }

    private static func roundTripStub(for suggestion: Suggestion) -> String? {
        guard suggestion.evidence.count >= 2,
              let forwardEvidence = suggestion.evidence.first,
              let reverseEvidence = suggestion.evidence.dropFirst().first,
              let forwardName = functionName(from: forwardEvidence.displayName),
              let inverseName = functionName(from: reverseEvidence.displayName),
              let forwardParam = paramType(from: forwardEvidence.signature) else {
            return nil
        }
        let seed = SamplingSeed.derive(from: suggestion.identity)
        return LiftedTestEmitter.roundTrip(
            forwardName: forwardName,
            inverseName: inverseName,
            seed: seed,
            generator: LiftedTestEmitter.defaultGenerator(for: forwardParam)
        )
    }

    /// Wrap the bare `@Test func` block from `LiftedTestEmitter` with
    /// the file-level imports + provenance header that the
    /// `Tests/Generated/SwiftInfer/` writeout needs.
    private static func wrappedFileContents(
        stub: String,
        suggestion: Suggestion
    ) -> String {
        let location = suggestion.evidence.first?.location
        let provenance = location.map { loc in "// Source: \(loc.file):\(loc.line)" } ?? ""
        return """
        // Auto-generated by `swift-infer discover --interactive` — do not edit.
        \(provenance)
        // Suggestion identity: \(suggestion.identity.display)
        // Template: \(suggestion.templateName)

        import Testing
        import PropertyBased
        import ProtocolLawKit
        \(stub)
        """
    }

    // MARK: - Suggestion field extraction

    /// Pull the function identifier out of a display name like
    /// `"normalize(_:)"` → `"normalize"`. Returns `nil` if the format
    /// doesn't match.
    static func functionName(from displayName: String) -> String? {
        guard let parenIndex = displayName.firstIndex(of: "(") else { return nil }
        let name = String(displayName[..<parenIndex])
        guard !name.isEmpty else { return nil }
        return name
    }

    /// Pull the first parameter type out of a signature like
    /// `"(String) -> String"` or `"(Money, Money) -> Money"`.
    /// Whitespace tolerant; returns `nil` if the parens are missing.
    static func paramType(from signature: String) -> String? {
        guard let openIndex = signature.firstIndex(of: "("),
              let closeIndex = signature.firstIndex(of: ")") else {
            return nil
        }
        let inside = signature[signature.index(after: openIndex)..<closeIndex]
        let trimmed = inside.trimmingCharacters(in: .whitespaces)
        if trimmed.isEmpty { return nil }
        let firstComponent = trimmed.split(separator: ",").first.map(String.init) ?? trimmed
        let stripped = firstComponent.trimmingCharacters(in: .whitespaces)
        return stripped.isEmpty ? nil : stripped
    }

    // MARK: - Decision record construction

    static func makeRecord(
        for suggestion: Suggestion,
        decision: Decision,
        timestamp: Date
    ) -> DecisionRecord {
        DecisionRecord(
            identityHash: suggestion.identity.normalized,
            template: suggestion.templateName,
            scoreAtDecision: suggestion.score.total,
            tier: suggestion.score.tier,
            decision: decision,
            timestamp: timestamp,
            signalWeights: suggestion.score.signals.map { signal in
                SignalSnapshot(kind: signal.kind.rawValue, weight: signal.weight)
            }
        )
    }

    // MARK: - File-name helpers

    private static func stubFileName(for suggestion: Suggestion) -> String? {
        guard let evidence = suggestion.evidence.first,
              let funcName = functionName(from: evidence.displayName) else {
            return nil
        }
        switch suggestion.templateName {
        case "round-trip":
            guard let reverse = suggestion.evidence.dropFirst().first,
                  let reverseName = functionName(from: reverse.displayName) else {
                return "\(funcName).swift"
            }
            return "\(funcName)_\(reverseName).swift"
        default:
            return "\(funcName).swift"
        }
    }
}
