import Foundation
import SwiftInferCore

/// Accept-path for M11.2 equivalence-class advisory suggestions
/// (PRD §7.8 third example). Comment-only documentation block —
/// no `@Test func` body, no runnable property. Split out of
/// `InteractiveTriage+Accept.swift` to keep that file under SwiftLint's
/// 400-line cap (the M11.2-budget-fix side-map dispatch + the writeout
/// helpers crossed the threshold).
extension InteractiveTriage {

    /// M11.2 — writeout for equivalence-class advisory suggestions.
    /// File path: `<outputDir>/Tests/Generated/SwiftInfer/equivalence-class/EquivalenceClasses_<predicate>.swift`.
    /// Honors `dryRun`.
    static func writeEquivalenceClassDocument(
        hint: EquivalenceClassHint,
        context: Context
    ) throws -> URL? {
        let fileName = "EquivalenceClasses_\(hint.predicateName).swift"
        let path = context.outputDirectory
            .appendingPathComponent("Tests/Generated/SwiftInfer/equivalence-class/\(fileName)")
        if context.dryRun {
            context.output.write("[dry-run] would write \(path.path)")
            return nil
        }
        let contents = equivalenceClassFileContents(hint: hint)
        try FileManager.default.createDirectory(
            at: path.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try Data(contents.utf8).write(to: path, options: .atomic)
        context.output.write("Wrote \(path.path)")
        return path
    }

    /// Formats the comment-only documentation block for an
    /// equivalence-class suggestion. Lists both bucket counts, the
    /// suggested filter generators (or the veto reason when the
    /// predicate is throws / async / multi-arg / non-generatable arg),
    /// and a caveat about filter rejection rate.
    static func equivalenceClassFileContents(hint: EquivalenceClassHint) -> String {
        var lines: [String] = []
        lines.append("// Auto-generated by `swift-infer discover --interactive` — do not edit.")
        lines.append("//")
        let header = "// Inferred predicate equivalence class for "
            + "\(hint.predicateName)(_: \(hint.argTypeName)) -> Bool"
        lines.append(header)
        lines.append("//")
        let positive = "//   • \(hint.positiveSiteCount) test methods named \(hint.positiveMarker)*"
            + " assert \(hint.predicateName)(x) is true"
        lines.append(positive)
        let negative = "//   • \(hint.negativeSiteCount) test methods named \(hint.negativeMarker)*"
            + " assert \(hint.predicateName)(x) is false"
        lines.append(negative)
        lines.append("//")
        if let veto = hint.predicateVeto {
            lines.append("// Generator narrowing skipped: \(veto.advisoryReason).")
        } else {
            let posGen = "// Suggested generator for \(hint.positiveMarker) class: "
                + hint.suggestedPositiveGenerator
            let negGen = "// Suggested generator for \(hint.negativeMarker) class: "
                + hint.suggestedNegativeGenerator
            lines.append(posGen)
            lines.append(negGen)
        }
        lines.append("//")
        let caveat = "// Caveat: \(hint.predicateName) may reject most random"
            + " \(hint.argTypeName)s; if so, prefer constructing a custom Gen for the"
            + " \(hint.positiveMarker) class instead of relying on filter."
        lines.append(caveat)
        return lines.joined(separator: "\n") + "\n"
    }
}
