import Foundation

/// File assembly for `KitSuiteEmitter`, split out for the 400-line cap.
extension KitSuiteEmitter {

    /// Wrap the per-carrier blocks in a compilable test file.
    ///
    /// The header states the counts up front because the interesting number is the one a
    /// reader would otherwise have to derive: how much of what the kit claims to cover this
    /// file actually reaches. A generated file that opens with "here are your tests" and
    /// quietly omits half is the failure mode this whole line of work has been correcting.
    static func assemble(
        live: [String],
        blocked: [String],
        moduleName: String,
        counts: KitSuiteEmitter.Counts,
        supportingDeclarations: [String] = []
    ) -> String {
        """
        \(header(counts))

        import Foundation
        import PropertyLawKit
        import SwiftInferKitEvidence
        import Testing
        @testable import \(moduleName)
        \(recursiveHelpers(supportingDeclarations))

        @Suite("PropertyLawKit conformance laws — \(moduleName)")
        struct Generated\(moduleName)KitSuites {

            /// Where `KitEvidenceRecorder` writes `.swiftinfer/kit-evidence.json`, so
            /// `discover` can read what these runs concluded. Derived from this file's own
            /// path rather than the working directory, which differs between `swift test`
            /// and an IDE.
            static var packageRoot: URL {
                var directory = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
                while directory.path != "/" {
                    let manifest = directory.appendingPathComponent("Package.swift")
                    if FileManager.default.fileExists(atPath: manifest.path) { return directory }
                    directory = directory.deletingLastPathComponent()
                }
                return URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            }

        \(live.joined(separator: "\n\n"))
        }

        // MARK: - Blocked on a generator
        //
        // Each of these needs `static func gen() -> Generator<T, some SendableSequenceType>`
        // on the carrier. The reason above each call is the kit's own diagnosis.

        \(blocked.joined(separator: "\n\n"))
        """
    }

    /// The provenance banner. Split out so `assemble` stays under the body-length cap, and
    /// because the counts are the part a reader must not miss: a generated file that opens
    /// with "here are your tests" and quietly omits half is the failure mode this whole line
    /// of work has been correcting.
    /// Depth-budgeted helper `func`s for recursive carriers, rendered at FILE SCOPE above
    /// the suite that calls them.
    ///
    /// **Why this exists.** A recursive carrier's generator expression cannot be inlined —
    /// it would have to contain itself — so `GeneratorResolver` emits
    /// `__gen<Type>(_ budget: Int)` and the expression *calls* it. This emitter rendered the
    /// call and dropped the declaration, so the scaffold wrote
    /// `using: __genMesh(4).array(of: 0...8).map { Mesh(submeshes: $0) }` with no `__genMesh`
    /// anywhere in the file. **Measured on `Euclid`: 20 of its 240 compile errors were this
    /// one symbol** (`docs/measurements/kit-scaffold-conversion.md` §3).
    ///
    /// The verify-stub emitter never had this bug —
    /// `StrategistDispatchEmitter.withRecursiveHelpers` carries the same declarations through
    /// `GeneratorRecipe.declarations`. **This side simply never read them**, which is why the
    /// fix is a render rather than a derivation: the helpers were built all along.
    ///
    /// File scope, not a member: they are free functions, and a nested `func` inside the
    /// `@Suite` struct would still compile but reads as a test helper rather than a generator.
    static func recursiveHelpers(_ declarations: [String]) -> String {
        guard !declarations.isEmpty else { return "" }
        return "\n// MARK: - Recursive-carrier generators\n//\n"
            + "// Depth-budgeted, because a recursive type's generator expression cannot\n"
            + "// contain itself. Called by the suites below.\n\n"
            + declarations.joined(separator: "\n\n")
    }

    static func header(_ counts: KitSuiteEmitter.Counts) -> String {
        """
        // Generated by `swift-infer scaffold-kit-suites`. REVIEW BEFORE USE — nothing here
        // was applied, run, or committed on your behalf.
        //
        // These are the laws PropertyLawKit's suites already cover for your types. They were
        // invisible before: `ProtocolCoverageMap` suppresses each one during `discover` with
        // a message naming `check<Protocol>PropertyLaws` and generating nothing, so the only
        // way to run them was to type every call site by hand.
        //
        //   \(counts.liveCarriers) carrier(s), \(counts.liveLaws) law(s)  — live below.
        //   \(counts.blockedCarriers) carrier(s), \(counts.blockedLaws) law(s)  — \
        commented out, each with its reason.
        //
        // The commented-out ones are not omissions, and they do not share one cause: a carrier
        // is blocked when its target's default isolation makes every conformance unusable,
        // when a generic cannot be named concretely, when the composed generator risks a
        // type-check timeout, or when no generator could be derived. Only the last is waiting
        // on a hand-written `gen()`. Read the reason on the block before acting on it — this
        // banner said "the generator could not be derived" for all four until 2026-08-13.
        //
        // NOT GUARANTEED TO COMPILE. A carrier may be `private` or nested past what
        // `@testable` reaches. Delete what does not fit.
        """
    }
}
