import Foundation

/// File assembly for `KitSuiteEmitter`, split out for the 400-line cap.
extension KitSuiteEmitter {

    /// Wrap the per-carrier blocks in a compilable test file.
    ///
    /// The header states the counts up front because the interesting number is the one a
    /// reader would otherwise have to derive: how much of what the kit claims to cover this
    /// file actually reaches. A generated file that opens with "here are your tests" and
    /// quietly omits half is the failure mode this whole line of work has been correcting.
    static func assemble(
        live: [String],
        blocked: [String],
        moduleName: String,
        counts: KitSuiteEmitter.Counts
    ) -> String {
        """
        \(header(counts))

        import Foundation
        import PropertyLawKit
        import SwiftInferKitEvidence
        import Testing
        @testable import \(moduleName)

        @Suite("PropertyLawKit conformance laws — \(moduleName)")
        struct Generated\(moduleName)KitSuites {

            /// Where `KitEvidenceRecorder` writes `.swiftinfer/kit-evidence.json`, so
            /// `discover` can read what these runs concluded. Derived from this file's own
            /// path rather than the working directory, which differs between `swift test`
            /// and an IDE.
            static var packageRoot: URL {
                var directory = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
                while directory.path != "/" {
                    let manifest = directory.appendingPathComponent("Package.swift")
                    if FileManager.default.fileExists(atPath: manifest.path) { return directory }
                    directory = directory.deletingLastPathComponent()
                }
                return URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            }

        \(live.joined(separator: "\n\n"))
        }

        // MARK: - Blocked on a generator
        //
        // Each of these needs `static func gen() -> Generator<T, some SendableSequenceType>`
        // on the carrier. The reason above each call is the kit's own diagnosis.

        \(blocked.joined(separator: "\n\n"))
        """
    }

    /// The provenance banner. Split out so `assemble` stays under the body-length cap, and
    /// because the counts are the part a reader must not miss: a generated file that opens
    /// with "here are your tests" and quietly omits half is the failure mode this whole line
    /// of work has been correcting.
    static func header(_ counts: KitSuiteEmitter.Counts) -> String {
        """
        // Generated by `swift-infer scaffold-kit-suites`. REVIEW BEFORE USE — nothing here
        // was applied, run, or committed on your behalf.
        //
        // These are the laws PropertyLawKit's suites already cover for your types. They were
        // invisible before: `ProtocolCoverageMap` suppresses each one during `discover` with
        // a message naming `check<Protocol>PropertyLaws` and generating nothing, so the only
        // way to run them was to type every call site by hand.
        //
        //   \(counts.liveCarriers) carrier(s), \(counts.liveLaws) law(s)  — live below.
        //   \(counts.blockedCarriers) carrier(s), \(counts.blockedLaws) law(s)  — \
        commented out: the generator could not be derived.
        //
        // The commented-out ones are not omissions. Each carries the kit's own reason, which
        // ends with the exact `gen()` signature to provide. Uncomment once you have written
        // it.
        //
        // NOT GUARANTEED TO COMPILE. `check<Protocol>PropertyLaws` requires `Value: Sendable`,
        // which the type shapes cannot always establish, and a carrier may be `private` or
        // nested past what `@testable` reaches. Delete what does not fit.
        """
    }
}
