import Foundation
import SwiftInferCore

/// Generators for SwiftSyntax node parameters, drawn from snippets the package's own tests parse.
///
/// One per `discover --interactive` run. Nothing is harvested until a stub asks for a node type,
/// and the corpus file is written beside the stubs the first time one uses it — a run over code
/// that takes no syntax nodes touches nothing. See `SyntaxSnippetHarvester` for what a snippet is
/// and why the tests are the source.
///
/// The emitted file declares one type, `SwiftInferSyntaxCorpus`, whose `gen(_:)` parses every
/// snippet, collects the nodes of the requested type and draws among them. It imports
/// `SwiftParser`, which a package analysing Swift already builds; a test target reaching it only
/// transitively still compiles under SwiftPM, measured on SwiftProjectLintVisitors.
final class SyntaxCorpusSource {

    static let typeName = "SwiftInferSyntaxCorpus"
    static let fileName = "\(typeName).swift"

    private let testRoots: [URL]
    private let destination: URL
    private let dryRun: Bool
    private lazy var corpus = SyntaxSnippetHarvester.harvest(roots: testRoots)
    private var written = false

    /// - Parameters:
    ///   - packageRoot: the package whose tests are harvested — every top-level directory named
    ///     `Tests` or ending in `Tests`.
    ///   - generatedRoot: the directory holding `SwiftInfer/`; the corpus file goes inside it.
    init(packageRoot: URL, generatedRoot: URL, dryRun: Bool) {
        // ⚠ **The enclosing repository's tests count too.** SwiftProjectLint's seven nested
        // packages hold no `Tests/` of their own — every one of its ~2,960 snippets lives in the
        // ROOT package's tests — so harvesting the scanned package alone found nothing for the 50
        // stubs that needed it, while SwiftEffectInference (tests in its own package) worked.
        self.testRoots = Self.testDirectories(of: packageRoot)
            + (Self.outermostPackageRoot(from: packageRoot).map(Self.testDirectories) ?? [])
        self.destination = generatedRoot
            .appendingPathComponent("SwiftInfer")
            .appendingPathComponent(Self.fileName)
        self.dryRun = dryRun
    }

    /// Test seam: a corpus supplied directly, written nowhere.
    init(corpus: SyntaxSnippetHarvester.Corpus) {
        self.testRoots = []
        self.destination = URL(fileURLWithPath: "/dev/null")
        self.dryRun = true
        self.corpus = corpus
    }

    /// Every top-level directory of `root` whose name ends in `Tests`.
    static func testDirectories(of root: URL) -> [URL] {
        let children = (try? FileManager.default.contentsOfDirectory(
            at: root,
            includingPropertiesForKeys: nil
        )) ?? []
        return children.filter { $0.lastPathComponent.hasSuffix("Tests") }
    }

    /// The outermost ancestor that is itself a SwiftPM package, or `nil` when `packageRoot` is
    /// not nested inside one. Bounded so a manifest far up a tree cannot drag in a whole disk.
    static func outermostPackageRoot(from packageRoot: URL, limit: Int = 4) -> URL? {
        var outermost: URL?
        var current = packageRoot
        for _ in 0 ..< limit {
            let parent = current.deletingLastPathComponent()
            guard parent.path != current.path else { break }
            if FileManager.default.fileExists(atPath: parent.appendingPathComponent("Package.swift").path) {
                outermost = parent
            }
            current = parent
        }
        return outermost
    }

    /// The generator expression for `typeName`, or `nil` when it is not a node type the corpus
    /// contains — the caller then falls through to its explained `.todo`.
    func generator(for typeName: String) -> String? {
        guard corpus.nodeTypeNames.contains(typeName) else { return nil }
        writeOnce()
        return "\(Self.typeName).gen(\(typeName).self)"
    }

    private func writeOnce() {
        guard !written, !dryRun else { return }
        written = true
        try? FileManager.default.createDirectory(
            at: destination.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try? Data(Self.fileContents(snippets: corpus.snippets).utf8).write(to: destination, options: .atomic)
    }

    /// The corpus file. Each snippet is a raw multi-line literal with enough `#`s that nothing in
    /// it can close the literal or start an interpolation.
    static func fileContents(snippets: [String]) -> String {
        let literals = snippets.map { snippet -> String in
            let hashes = String(repeating: "#", count: rawDelimiterCount(for: snippet))
            return "        \(hashes)\"\"\"\n\(snippet)\n\"\"\"\(hashes)"
        }
        return """
        // Auto-generated by `swift-infer discover --interactive` — do not edit.
        // Swift snippets harvested from this package's own tests, each of which parses without
        // error. Generated laws over SwiftSyntax nodes draw their inputs from here.

        import Foundation
        import PropertyBased
        import SwiftParser
        import SwiftSyntax

        enum \(typeName) {
            static let snippets: [String] = [
        \(literals.joined(separator: ",\n"))
            ]

        \(machinery)
        }

        """
    }

    /// The corpus type's fixed half: parse once, collect per node type, draw among the results.
    ///
    /// A constant rather than more lines of `fileContents`, which SwiftLint's body-length cap
    /// reached the moment the cache landed in it.
    private static let machinery = """
            private final class Collector<Node: SyntaxProtocol>: SyntaxAnyVisitor {
                var found: [Node] = []

                override func visitAny(_ node: Syntax) -> SyntaxVisitorContinueKind {
                    if let match = node.as(Node.self) { found.append(match) }
                    return .visitChildren
                }
            }

            /// ⚠ **Parsed once, collected once per node type.** A stub calls `gen(_:)` inside its
            /// per-trial closure, so a corpus re-parsed per call costs trials × snippets parses —
            /// measured at over a million for one package, which reads as a hang rather than as
            /// a slow generator.
            private static let trees: [SourceFileSyntax] = snippets.map { Parser.parse(source: $0) }

            private final class Cache: @unchecked Sendable {
                private let lock = NSLock()
                private var storage: [ObjectIdentifier: Any] = [:]

                func nodes<Node: SyntaxProtocol>(_ type: Node.Type, build: () -> [Node]) -> [Node] {
                    lock.lock()
                    defer { lock.unlock() }
                    if let hit = storage[ObjectIdentifier(type)] as? [Node] { return hit }
                    let built = build()
                    storage[ObjectIdentifier(type)] = built
                    return built
                }
            }

            private static let cache = Cache()

            /// Every node of type `Node` in the corpus, in source order.
            static func nodes<Node: SyntaxProtocol>(_ type: Node.Type) -> [Node] {
                cache.nodes(type) {
                    trees.flatMap { tree -> [Node] in
                        let collector = Collector<Node>(viewMode: .sourceAccurate)
                        collector.walk(tree)
                        return collector.found
                    }
                }
            }

            /// A generator drawing among every `Node` the corpus contains. The tool offers this
            /// only for a type it found at least once, so the range is never empty.
            static func gen<Node: SyntaxProtocol>(_ type: Node.Type) -> Generator<Node, some SendableSequenceType> {
                let all = nodes(type)
                return Gen<Int>.int(in: 0 ... max(all.count - 1, 0)).map { all[$0] }
            }
    """

    /// The fewest `#`s such that `"""` + hashes and `\` + hashes never occur in `snippet`.
    static func rawDelimiterCount(for snippet: String) -> Int {
        var count = 1
        while snippet.contains("\"\"\"" + String(repeating: "#", count: count))
                || snippet.contains("\\" + String(repeating: "#", count: count)) {
            count += 1
        }
        return count
    }
}
